export const usersData = [
    {
      name: "Alice Johnson",
      email: "alice@university.com",
      role: "Student",
      community: "Android",
      course: "Software Engineering",
    },
    {
      name: "Michael Smith",
      email: "michael@university.com",
      role: "Community Lead",
      community: "Web Development",
      course: "Computer Science",
    },
    {
      name: "Dr. Susan Lee",
      email: "susan@university.com",
      role: "Lecturer",
      community: "Graphics Design",
      course: "Multimedia Design",
    },
    {
      name: "John Doe",
      email: "john@university.com",
      role: "Executive",
      community: "AI & Data Science",
      course: "Data Science",
    },
    {
      name: "Emma Watson",
      email: "emma@university.com",
      role: "Student",
      community: "Web Development",
      course: "Computer Science",
    },
    {
      name: "Robert Brown",
      email: "robert@university.com",
      role: "Student",
      community: "Android",
      course: "Software Engineering",
    },
    {
      name: "Linda Davis",
      email: "linda@university.com",
      role: "Community Lead",
      community: "Graphics Design",
      course: "Digital Media",
    },
    {
      name: "James Wilson",
      email: "james@university.com",
      role: "Lecturer",
      community: "Web Development",
      course: "Information Systems",
    },
    {
      name: "Patricia Taylor",
      email: "patricia@university.com",
      role: "Executive",
      community: "AI & Data Science",
      course: "Data Science",
    },
    {
      name: "Michael Jordan",
      email: "michael.j@university.com",
      role: "Student",
      community: "Android",
      course: "Mobile App Development",
    },
    {
      name: "Sarah Miller",
      email: "sarah@university.com",
      role: "Community Lead",
      community: "AI & Data Science",
      course: "Machine Learning",
    },
    {
      name: "William Martinez",
      email: "william@university.com",
      role: "Lecturer",
      community: "Graphics Design",
      course: "Visual Communication",
    },
  ];
  